# $File: //ASP/tec/epics/boxStatus/trunk/BoxStatusSup/Makefile $
# $Revision: #2 $
# $DateTime: 2022/05/21 12:45:50 $
# Last checked in by: $Author: starritt $
#

TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *src*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *Db*))
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *opi*))
include $(TOP)/configure/RULES_DIRS

# end
