# $File: //ASP/tec/epics/boxStatus/trunk/BoxStatusSup/opi/Makefile $
# $Revision: #2 $
# $DateTime: 2022/07/19 16:08:12 $
# Last checked in by: $Author: starritt $
#

TOP = ../..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *qeui*))
include $(TOP)/configure/RULES_DIRS

# end
